### ISSUE TITLE
Cannot setup in minikube

### ISSUE THREAD

**Issue by subpop** [RedHatInsights/clowder#595]
## Description

The `kube_setup.sh` script fails to deploy the strimzi operator in minikube.

## Steps to Reproduce

1. `minikube start --cpus 4 --disk-size 36GB --memory 8000MB --addons=registry --addons=ingress --driver=kvm2`
2. `bash ./build/kube_setup.sh`

## Expected Results

All pods running.

## Actual Results

All pods but `strimzi-cluster-operator` are running; `strimzi-cluster-operator` is in a CrashBackoffLoop.

```minikube kubectl -- --namespace strimzi logs Deployments/strimzi-cluster-operator
2022-04-19 22:04:18 ERROR Main:153 - Cluster Operator verticle in namespace * failed to start
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/kafka.strimzi.io/v1beta2/kafkas?watch=true. Message: kafkas.kafka.strimzi.io is forbidden: User "system:serviceaccount:strimzi:strimzi-cluster-operator" cannot watch resource "kafkas" in API group "kafka.strimzi.io" at the cluster scope. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=kafka.strimzi.io, kind=kafkas, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=kafkas.kafka.strimzi.io is forbidden: User "system:serviceaccount:strimzi:strimzi-cluster-operator" cannot watch resource "kafkas" in API group "kafka.strimzi.io" at the cluster scope, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:693) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:672) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
        at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onFailure(WatcherWebSocketListener.java:74) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[com.squareup.okhttp3.okhttp-3.12.6.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
        Suppressed: java.lang.Throwable: waiting here
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:164) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
                at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:175) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.waitUntilReady(WatcherWebSocketListener.java:120) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:80) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:682) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:657) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
                at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:89) ~[io.fabric8.kubernetes-client-5.8.0.jar:?]
                at io.strimzi.operator.common.operator.resource.AbstractWatchableResourceOperator.watch(AbstractWatchableResourceOperator.java:61) ~[io.strimzi.operator-common-0.26.0.jar:0.26.0]
                at io.strimzi.operator.common.AbstractOperator.lambda$createWatch$18(AbstractOperator.java:440) ~[io.strimzi.operator-common-0.26.0.jar:0.26.0]
                at io.strimzi.operator.common.Util.lambda$async$0(Util.java:76) ~[io.strimzi.operator-common-0.26.0.jar:0.26.0]
                at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]
                at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]
                at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]
                at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.1.5.jar:4.1.5]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.68.Final.jar:4.1.68.Final]
                at java.lang.Thread.run(Thread.java:829) [?:?]
```

## Additional Details

* minikube version 1.25.2, commit 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
* Fedora 35
* kube_setup.sh version https://github.com/RedHatInsights/clowder/blob/49af63d34dddb74737d622b00b53b3a19fffa315/build/kube_setup.sh

**Comment by bsquizz** [comment]
Do you have the logs from when this section of the script was run:
https://github.com/RedHatInsights/clowder/blob/master/build/kube_setup.sh#L108

I am wondering if there were any errors applying those cluster role bindings.

**Comment by bsquizz** [comment]
Basically the script is following the directions outlined here: https://strimzi.io/docs/operators/in-development/full/deploying.html#deploying-cluster-operator-to-watch-whole-cluster-str

**Comment by bsquizz** [comment]
Root cause:

Strimzi manifests have ClusterRoleBinding's api version as v1beta1. ClusterRoleBinding is no longer in rbac v1beta1

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122

I'd suggest running on kubernetes < v1.22 until they release updated manifests.

**Comment by subpop** [comment]
That was it. Starting minikube with `--kubernetes-version=v1.21.4` allows the `kube_setup.sh` script to run correctly.

**Comment by bsquizz** [comment]
Actually when looking again, strimzi's manifests DO use `v1`. The problem was likely due to an old kubectl client version that was creating a `v1beta1` ClusterRoleBinding when the `kubectl create clusterrolebinding` command was executed.
